repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: conda-enviroment
        name: custom-conda-enviroment-checker
        entry: bash ./conda_saver.sh
        language: system
