#!/bin/bash
#
# Submit a small A100 reconstruction smoke over methods that do not require a
# newly trained PnP denoiser. This reuses the normal reconstruction array
# submitter so the smoke exercises the same matrix and job script as full runs.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export PADIS_RECON_METHODS="${PADIS_RECON_METHODS:-baseline,admm_tv,padis_dps,langevin,predictor_corrector,ve_ddnm}"
export PADIS_RECON_MODELS="${PADIS_RECON_MODELS:-method_default}"
export PADIS_RECON_EXPERIMENTS="${PADIS_RECON_EXPERIMENTS:-ct_20}"
export PADIS_RECON_IMPLEMENTATIONS="${PADIS_RECON_IMPLEMENTATIONS:-lion_physics}"
export PADIS_RECON_GEOMETRIES="${PADIS_RECON_GEOMETRIES:-lion}"
export PADIS_RECON_MAX_SAMPLES="${PADIS_RECON_MAX_SAMPLES:-1}"
export PADIS_RECON_START_INDEX="${PADIS_RECON_START_INDEX:-0}"
export PADIS_RECON_SAVE_PREVIEWS="${PADIS_RECON_SAVE_PREVIEWS:-1}"
export PADIS_RECON_PROG_BAR="${PADIS_RECON_PROG_BAR:-1}"
export PADIS_RECON_TRACE_IMAGES="${PADIS_RECON_TRACE_IMAGES:-1}"
export PADIS_RECON_TRACE_INTERVAL="${PADIS_RECON_TRACE_INTERVAL:-20}"
export PADIS_RECON_TIME="${PADIS_RECON_TIME:-02:00:00}"
export PADIS_RECON_ARRAY_LIMIT="${PADIS_RECON_ARRAY_LIMIT:-3}"
export PADIS_RECON_VERIFY="${PADIS_RECON_VERIFY:-1}"
export PADIS_RECON_VERIFY_METHODS="${PADIS_RECON_VERIFY_METHODS:-$PADIS_RECON_METHODS}"
export PADIS_RECON_VERIFY_EXPERIMENTS="${PADIS_RECON_VERIFY_EXPERIMENTS:-$PADIS_RECON_EXPERIMENTS}"
export PADIS_RECON_VERIFY_GEOMETRIES="${PADIS_RECON_VERIFY_GEOMETRIES:-$PADIS_RECON_GEOMETRIES}"
smoke_quality_methods="${PADIS_RECON_SMOKE_QUALITY_METHODS:-admm_tv,padis_dps,langevin,predictor_corrector,ve_ddnm}"
export PADIS_RECON_VERIFY_REQUIRE_METHOD_MEAN_BETTER_THAN_FDK="${PADIS_RECON_VERIFY_REQUIRE_METHOD_MEAN_BETTER_THAN_FDK:-$smoke_quality_methods}"
export PADIS_RECON_VERIFY_REQUIRE_METHOD_EACH_BETTER_THAN_FDK="${PADIS_RECON_VERIFY_REQUIRE_METHOD_EACH_BETTER_THAN_FDK:-$smoke_quality_methods}"
export PADIS_RECON_VERIFY_MIN_METHOD_MEAN_PSNR="${PADIS_RECON_VERIFY_MIN_METHOD_MEAN_PSNR:-admm_tv=28 padis_dps=33 langevin=32 predictor_corrector=29 ve_ddnm=32}"

exec "$SCRIPT_DIR/submit_PaDIS_A100_reconstruction.sh"
